In [1]:
import numpy as np
import random

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
    
def derivative_sigmoid(x):
    return x*(1-x)
    
def relu(x):
    return np.maximum(0,x)
    
def derivative_relu(x):
    a=x
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i][j] >0:
                a[i][j]=1
            else:
                a[i][j]=0
    return a 

def predict(w1,w2,w3,b1,b2,b3,x_test):
    z1 = np.dot(w1,x_test.T)+b1
    a1 = relu(z1)
    z2 = np.dot(w2,a1)+b2
    a2 = relu(z2)
    z3 = np.dot(w3,a2)+b3
    output = sigmoid(z3)
    return output
    
    

class MYNN:
    def __init__(self,layers,x,y,learning_rate=0.001):
        
        m = x.shape[0]
        
        self.w1 = np.random.rand(layers[1],layers[0])
        self.b1 = np.random.rand(layers[1],1)
        
        self.w2 = np.random.rand(layers[2],layers[1])
        self.b2 = np.random.rand(layers[2],1)
        
        self.w3 = np.random.rand(layers[3],layers[2])
        self.b3 = np.random.rand(layers[3],1)
        
        self.input = x.T
        self.y = y
        
        self.output = np.zeros(y.shape)
        
        self.alpha = learning_rate
        
    
    def forwardpropogation(self):
        
        self.z1 = np.dot(self.w1,self.input)+self.b1
        self.a1 = relu(self.z1)
        
        self.z2 = np.dot(self.w2,self.a1)+self.b2
        self.a2 =  relu(self.z2)
        
        self.z3 = np.dot(self.w3,self.a2)+self.b3
        self.output = sigmoid(self.z3)
    
    def backwardpropogation(self):

        self.dz3 = self.output-self.y
        self.dw3 = 1/self.y.shape[1]*np.dot(self.dz3,self.a2.T)
        self.db3 = 1/self.y.shape[1]*np.sum(self.dz3,axis=1,keepdims=True)
        
        self.dz2 = np.dot(self.dw3.T,self.dz3)*derivative_relu(self.z2)
        self.dw2 = 1/self.y.shape[1]*np.dot(self.dz2,self.a1.T)
        self.db2 = 1/self.y.shape[1]*np.sum(self.dz2,axis=1,keepdims=True)
        
        self.dz1 = np.dot(self.dw2.T,self.dz2)*derivative_relu(self.z1)
        self.dw1 = 1/self.y.shape[1]*np.dot(self.dz1,self.input.T)
        self.db1 = 1/self.y.shape[1]*np.sum(self.dz1,axis=1,keepdims=True)
        
        self.w1=self.w1-self.alpha*self.dw1
        self.b1=self.b1-self.alpha*self.db1
        
        self.w2=self.w2-self.alpha*self.dw2
        self.b2=self.b2-self.alpha*self.db2
        
        self.w3=self.w3-self.alpha*self.dw3
        self.b3=self.b3-self.alpha*self.db3
        
        return self.w1,self.b1,self.w2,self.b2,self.w3,self.b3
        
    def cost(self):
        cost=-1/self.y.shape[1]*np.sum((self.y*np.log(self.output)+(1-self.y)*np.log(1-self.output)))
        print(cost)
        return cost
    

In [20]:
layers=[3,4,5,1]
x=np.array([[0,1,2],[1,2,1],[3,4,6],[0,0,1],[1,0,1],[1,5,5],[6,1,4],[1,1,2],[2,1,1],[3,1,8]])

y=np.array([[0,0,1,0,0,1,1,0,0,1]])
print(x.shape)
nn= MYNN(layers,x,y)
cost=[]
for i in range(10000):
    nn.forwardpropogation()
    w1,b1,w2,b2,w3,b3=nn.backwardpropogation()
    cost.append(nn.cost())

(10, 3)
nan
nan
nan
7.288527262402123
6.9644192897200385
6.6815879227054324
6.4317509949238065
6.208811640487525
6.008162074114001
5.826242379769784
5.6602502429722215
5.5079438682869934
5.367504507950488
5.237438305243294
5.11650476248156
5.003663663212925
4.898035050725525
4.798868614540004
4.705519968145176
4.617432049856297
4.534120383855487
4.455161285641947
4.380182315132478
4.308854531632827
4.240886189756529
4.176017404104676
4.114015808224657
4.054672933213833
3.9978010820084258
3.943230740334185
3.8908083608125654
3.8403944688805733
3.791862044191521
3.745095114601894
3.69998754597529
3.656441989471513
3.614368963788588
3.5736860523231755
3.534317198580397
3.496192085895618
3.459245589769614
3.423417292955854
3.3886510549549977
3.3548946288281307
3.3220993014753812
3.2902196121476575
3.2592130990460215
3.229040008486932
3.199663071668507
3.1710472211680414
3.1431597422659525
3.1159697697263207
3.0894482492792528
3.0635678027454176
3.0383026052763706
3.013628273441514
2.989521

C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\ipykernel_launcher.py:90: RuntimeWarning: divide by zero encountered in log
C:\Users\Srujan\Anaconda\anaconda3\lib\site-packages\ipykernel_launcher.py:90: RuntimeWarning: invalid value encountered in multiply



1.9503785422132527
1.9433821941511014
1.93645013107054
1.929581374367012
1.9227749665971303
1.9160299708914588
1.909345470387072
1.9027205676790908
1.8961543842904842
1.8896460601593643
1.883194753143146
1.8767996385389065
1.870459908619311
1.8641747721835256
1.8579434541225408
1.8517651949983671
1.8456392506365853
1.8395648917317453
1.8335414034651447
1.8275680851345268
1.821644249795276
1.8157692239126644
1.8099423470247773
1.804162971415718
1.7984304617987257
1.792744195008865
1.7871035597049225
1.7815079560802265
1.775956795582018
1.7704495006391565
1.7650054080151643
1.7596306313839385
1.7542969589205608
1.7490038788634454
1.743750888566159
1.7385374942875058
1.7333632109874604
1.728227562128812
1.723130079484272
1.7180703029489355
1.7130477803578625
1.70806206730866
1.703112726988868
1.6981993300080263
1.6933214542342645
1.688478684635253
1.6836706131234136
1.6788968384052254
1.6741569658345137
1.6694506072696005
1.66477738093419
1.6601369112818738
1.6555288288641563
1.650952770

0.8108849478489312
0.8103104799040795
0.8097379080749104
0.8091672267065232
0.8085984301579693
0.8080315128021911
0.8074664690259653
0.8069032932298432
0.8063419798280939
0.8057825232486453
0.8052249179330299
0.8046691583363267
0.8041152389271066
0.8035631541873764
0.8030128986125251
0.8024644667112684
0.8019178530055971
0.8013730520307214
0.8008300583350207
0.8002888664799901
0.7997494710401889
0.7992118666031893
0.7986760477695267
0.7981420091526483
0.7976097453788644
0.797079251087298
0.7965505209298378
0.796023549571088
0.795498331688322
0.7949748619714339
0.7944531351228932
0.7939331458576965
0.7934148889033235
0.7928983589996896
0.7923835508991027
0.7918704593662174
0.7913590791779912
0.7908494051236412
0.7903414320046004
0.7898351546344753
0.7893305678390031
0.7888276664560112
0.7883264453353731
0.7878268993389702
0.7873290233406491
0.7868328122261827
0.7863382608932301
0.7858453642512968
0.7853541172216963
0.7848645147375116
0.7843767254353887
0.7838907949756786
0.7834064885801

0.6741723249384509
0.67404876534645
0.6739255383664258
0.6738026425619204
0.6736800765021527
0.6735578387620027
0.6734359279219958
0.6733143425682853
0.6731930812926362
0.67307214269241
0.672951525370546
0.6728312279355473
0.6727112490014631
0.6725915871878726
0.6724722411198685
0.6723532094280406
0.6722344907484602
0.6721160837226625
0.6719979869976312
0.6718801992257817
0.6717627190649443
0.6716455451783494
0.6715286762346094
0.6714121109077036
0.6712958478769608
0.6711798858270444
0.6710642234479344
0.6709488594349128
0.6708337924885459
0.670719021314669
0.6706045446243696
0.670490361133971
0.6703764695650171
0.6702628686442544
0.6701495571036176
0.6700365336802122
0.6699237971162983
0.6698113461592755
0.6696991795616655
0.6695872960810961
0.6694756944802859
0.6693643735270274
0.6692533319941707
0.6691425686596084
0.6690320823062581
0.668921871722048
0.6688119356998987
0.668702273037709
0.6685928825383394
0.6684837630095951
0.6683749132642112
0.6682663321198362
0.6681580183990161
0.

0.6319929706801983
0.6319390696340181
0.6318852018503291
0.6318313672185358
0.6317775656285809
0.6317237969709433
0.6316700611366343
0.6316163580171963
0.6315626875046991
0.6315090494917381
0.6314554438714312
0.6314018705374161
0.6313483293838482
0.6312948203053983
0.6312413431972479
0.6311878979550901
0.631134484475124
0.6310811026540543
0.6310277523890874
0.6309744335779295
0.630921146118784
0.6308678899103494
0.6308146648518163
0.6307614708428652
0.6307083077836636
0.6306551755748648
0.6306020741176044
0.6305490033134978
0.6304959630646387
0.6304429532735959
0.6303899738434113
0.6303370246775979
0.6302841056801363
0.6302312167554741
0.6301783578085216
0.6301255287446512
0.6300727294696942
0.6300199598899382
0.6299672199121266
0.6299145094434536
0.6298618283915642
0.6298091766645513
0.6297565541709527
0.6297039608197497
0.629651396520365
0.6295988611826604
0.6295463547169334
0.6294938770339171
0.6294414280447762
0.6293890076611061
0.6293366157949296
0.629284252358696
0.62923191726527

0.6068953419816688
0.6068512858942992
0.6068072420206354
0.606763210349079
0.6067191908680709
0.6066751835660908
0.6066311884316575
0.6065872054533276
0.6065432346196964
0.6064992759193973
0.6064553293411019
0.6064113948735191
0.6063674725053955
0.6063235622255153
0.6062796640226998
0.6062357778858076
0.6061919038037336
0.6061480417654097
0.6061041917598045
0.6060603537759227
0.6060165278028051
0.6059727138295287
0.6059289118452059
0.6058851218389851
0.6058413438000505
0.6057975777176207
0.6057538235809498
0.6057100813793274
0.6056663511020767
0.6056226327385569
0.6055789262781607
0.6055352317103154
0.6054915490244821
0.6054478782101566
0.6054042192568676
0.6053605721541782
0.6053169368916842
0.6052733134590156
0.6052297018458348
0.6051861020418374
0.605142514036752
0.6050989378203395
0.605055373382394
0.6050118207127412
0.6049682798012395
0.604924750637779
0.6048812332122819
0.6048377275147023
0.6047942335350256
0.6047507512632688
0.6047072806894801
0.6046638218037389
0.60462037459615

0.5843990516517769
0.5843605670043617
0.584322091162348
0.5842836241220443
0.5842451658797628
0.58420671643182
0.5841682757745364
0.5841298439042368
0.5840914208172494
0.5840530065099071
0.5840146009785466
0.5839762042195087
0.5839378162291378
0.5838994370037829
0.5838610665397964
0.5838227048335353
0.5837843518813598
0.5837460076796345
0.5837076722247282
0.5836693455130127
0.5836310275408646
0.5835927183046643
0.5835544178007954
0.5835161260256462
0.5834778429756081
0.5834395686470771
0.5834013030364523
0.5833630461401373
0.5833247979545391
0.5832865584760686
0.5832483277011404
0.5832101056261729
0.5831718922475887
0.5831336875618133
0.5830954915652768
0.5830573042544128
0.5830191256256582
0.5829809556754538
0.5829427944002447
0.5829046417964786
0.582866497860608
0.5828283625890885
0.5827902359783791
0.582752118024943
0.5827140087252468
0.5826759080757608
0.5826378160729586
0.5825997327133179
0.5825616579933197
0.5825235919094486
0.5824855344581928
0.5824474856360443
0.582409445439498

0.5682692249899508
0.5682343021875316
0.5681993868451193
0.5681644789601183
0.5681295785299344
0.568094685551975
0.568059800023649
0.568024921942367
0.5679900513055411
0.5679551881105852
0.5679203323549146
0.5678854840359457
0.5678506431510972
0.5678158096977892
0.567780983673443
0.5677461650754817
0.5677113539013298
0.5676765501484138
0.5676417538141613
0.5676069648960013
0.5675721833913647
0.5675374092976841
0.5675026426123934
0.5674678833329277
0.5674331314567241
0.5673983869812214
0.5673636499038592
0.5673289202220791
0.5672941979333246
0.5672594830350398
0.5672247755246711
0.5671900753996661
0.5671553826574742
0.5671206972955458
0.5670860193113331
0.5670513487022899
0.5670166854658715
0.5669820295995346
0.5669473811007373
0.5669127399669396
0.5668781061956024
0.5668434797841888
0.5668088607301629
0.5667742490309903
0.5667396446841384
0.5667050476870761
0.5666704580372732
0.5666358757322018
0.5666013007693349
0.5665667331461471
0.5665321728601149
0.5664976199087155
0.56646307428942

0.5530165567943448
0.5529848009222764
0.5529530514597512
0.5529213084047343
0.5528895717551914
0.5528578415090893
0.552826117664396
0.5527944002190802
0.5527626891711119
0.5527309845184616
0.5526992862591009
0.5526675943910029
0.5526359089121409
0.5526042298204896
0.5525725571140244
0.5525408907907223
0.5525092308485605
0.5524775772855176
0.552445930099573
0.5524142892887068
0.552382654850901
0.5523510267841374
0.5523194050863997
0.5522877897556716
0.5522561807899388
0.5522245781871872
0.5521929819454041
0.5521613920625774
0.5521298085366961
0.5520982313657504
0.5520666605477312
0.5520350960806304
0.5520035379624406
0.551971986191156
0.5519404407647709
0.5519089016812816
0.551877368938684
0.5518458425349763
0.5518143224681569
0.551782808736225
0.5517513013371815
0.5517198002690274
0.5516883055297652
0.5516568171173984
0.5516253350299308
0.5515938592653681
0.5515623898217158
0.5515309266969812
0.5514994698891724
0.5514680193962984
0.5514365752163688
0.5514051373473945
0.5513737057873874

0.5396939726730752
0.5396648419216842
0.5396357167723626
0.5396065972234405
0.5395774832732493
0.5395483749201202
0.5395192721623862
0.5394901749983798
0.5394610834264354
0.539431997444887
0.5394029170520704
0.5393738422463213
0.5393447730259767
0.5393157093893736
0.5392866513348502
0.5392575988607459
0.5392285519653996
0.539199510647152
0.5391704749043436
0.5391414447353166
0.5391124201384131
0.5390834011119762
0.53905438765435
0.5390253797638788
0.5389963774389079
0.5389673806777834
0.5389383894788514
0.5389094038404599
0.5388804237609567
0.5388514492386908
0.5388224802720112
0.5387935168592687
0.5387645589988135
0.5387356066889978
0.5387066599281737
0.5386777187146942
0.5386487830469129
0.5386198529231843
0.5385909283418635
0.5385620093013064
0.5385330957998694
0.5385041878359099
0.5384752854077857
0.5384463885138554
0.5384174971524782
0.5383886113220144
0.5383597310208246
0.5383308562472701
0.5383019869997135
0.538273123276517
0.5382442650760444
0.5382154123966598
0.538186565236728

0.5269665040997339
0.5269397652111278
0.5269130312313343
0.5268863021589704
0.5268595779926536
0.5268328587310024
0.526806144372636
0.5267794349161732
0.5267527303602345
0.5267260307034404
0.5266993359444115
0.5266726460817698
0.5266459611141372
0.5266192810401367
0.5265926058583914
0.5265659355675252
0.5265392701661623
0.5265126096529279
0.5264859540264472
0.5264593032853461
0.5264326574282513
0.52640601645379
0.5263793803605896
0.5263527491472785
0.5263261228124853
0.5262995013548396
0.5262728847729706
0.5262462730655092
0.5262196662310861
0.5261930642683327
0.5261664671758812
0.526139874952364
0.5261132875964142
0.5260867051066654
0.5260601274817519
0.5260335547203082
0.5260069868209699
0.5259804237823725
0.5259538656031525
0.5259273122819467
0.5259007638173924
0.5258742202081278
0.5258476814527914
0.5258211475500221
0.5257946184984594
0.5257680942967438
0.5257415749435154
0.525715060437416
0.525688550777087
0.5256620459611708
0.5256355459883102
0.5256090508571484
0.5255825605663296

0.5154839545740603
0.5154592797845436
0.5154346093366516
0.5154099432292212
0.5153852814610899
0.5153606240310955
0.5153359709380768
0.5153113221808722
0.515286677758321
0.515262037669263
0.5152374019125386
0.5152127704869877
0.5151881433914517
0.5151635206247718
0.5151389021857903
0.515114288073349
0.5150896782862908
0.515065072823459
0.5150404716836972
0.5150158748658494
0.5149912823687599
0.5149666941912737
0.5149421103322362
0.5149175307904933
0.5148929555648908
0.5148683846542758
0.514843818057495
0.5148192557733962
0.5147946978008273
0.5147701441386362
0.5147455947856724
0.5147210497407849
0.5146965090028232
0.5146719725706371
0.5146474404430779
0.514622912618996
0.5145983890972431
0.5145738698766709
0.5145493549561314
0.5145248443344775
0.5145003380105626
0.5144758359832399
0.5144513382513632
0.5144268448137874
0.5144023556693668
0.5143778708169571
0.5143533902554139
0.514328913983593
0.5143044420003513
0.5142799743045458
0.5142555108950335
0.5142310517706726
0.5142065969303212


0.5042779061642458
0.5042551623954855
0.5042324224635982
0.5042096863676061
0.5041869541065316
0.5041642256793974
0.5041415010852267
0.5041187803230431
0.5040960633918702
0.5040733502907322
0.5040506410186535
0.5040279355746593
0.5040052339577744
0.5039825361670246
0.5039598422014356
0.5039371520600339
0.5039144657418458
0.5038917832458986
0.5038691045712194
0.5038464297168356
0.5038237586817753
0.5038010914650671
0.5037784280657395
0.5037557684828214
0.503733112715342
0.5037104607623316
0.5036878126228197
0.5036651682958369
0.5036425277804139
0.5036198910755818
0.5035972581803722
0.5035746290938165
0.5035520038149469
0.5035293823427962
0.5035067646763969
0.5034841508147821
0.5034615407569855
0.503438934502041
0.5034163320489825
0.5033937333968445
0.5033711385446622
0.5033485474914705
0.5033259602363052
0.5033033767782019
0.503280797116197
0.5032582212493272
0.5032356491766291
0.5032130808971402
0.5031905164098982
0.5031679557139407
0.5031453988083062
0.5031228456920332
0.5031002963641

0.4942689365425883
0.4942478495623182
0.49422676600593435
0.4942056858726027
0.49418460916148926
0.49416353587176076
0.49414246600258355
0.494121399553125
0.49410033652255225
0.49407927691003295
0.49405822071473493
0.4940371679358264
0.4940161185724759
0.4939950726238519
0.4939740300891238
0.4939529909674605
0.4939319552580318
0.49391092296000727
0.4938898940725574
0.4938688685948527
0.4938478465260633
0.49382682786536053
0.49380581261191586
0.4937848007649005
0.4937637923234863
0.4937427872868454
0.4937217856541503
0.4937007874245736
0.4936797925972882
0.49365880117146743
0.49363781314628474
0.49361682852091376
0.4935958472945287
0.493574869466304
0.49355389503541414
0.4935329240010341
0.49351195636233913
0.49349099211850445
0.4934700312687061
0.49344907381211983
0.493428119747922
0.49340716907528936
0.49338622179339864
0.493365277901427
0.4933443373985519
0.493323400283951
0.4933024665568021
0.49328153621628384
0.49326060926157445
0.4932396856918526
0.49321876550629784
0.493197848704

0.48513319913863695
0.4851135696403237
0.4850939432181212
0.48507431987131133
0.48505469959917547
0.4850350824009959
0.4850154682760547
0.4849958572236342
0.4849762492430172
0.4849566443334865
0.48493704249432545
0.4849174437248174
0.48489784802424574
0.48487825539189444
0.48485866582704784
0.4848390793289899
0.4848194958970051
0.48479991553037866
0.4847803382283952
0.4847607639903402
0.4847411928154987
0.48472162470315694
0.48470205965260055
0.4846824976631157
0.484662938733989
0.48464338286450687
0.48462383005395604
0.484604280301624
0.4845847336067978
0.484565189968765
0.48454564938681355
0.4845261118602313
0.48450657738830655
0.48448704597032766
0.4844675176055835
0.484447992293363
0.48442847003295536
0.4844089508236497
0.48438943466473594
0.4843699215555039
0.4843504114952435
0.4843309044832451
0.4843114005187995
0.4842918996011972
0.48427240172972924
0.4842529069036869
0.48423341512236173
0.48421392638504535
0.48419444069102974
0.48417495803960675
0.48415547843006934
0.4841360018

0.4764172090646467
0.47639892231630476
0.47638063833671834
0.47636235712526614
0.4763440786813282
0.47632580300428373
0.47630753009351284
0.47628925994839544
0.4762709925683119
0.4762527279526425
0.476234466100768
0.47621620701206907
0.47619795068592685
0.47617969712172253
0.4761614463188374
0.47614319827665325
0.47612495299455165
0.4761067104719146
0.4760884707081243
0.4760702337025633
0.47605199945461385
0.4760337679636588
0.4760155392290812
0.47599731325026395
0.47597909002659056
0.47596086955744427
0.47594265184220896
0.47592443688026864
0.47590622467100724
0.475888015213809
0.47586980850805843
0.4758516045531403
0.47583340334843927
0.4758152048933404
0.4757970091872289
0.47577881622949036
0.47576062601951014
0.47574243855667425
0.47572425384036854
0.47570607186997926
0.47568789264489264
0.47566971616449544
0.47565154242817426
0.47563337143531625
0.47561520318530826
0.4755970376775376
0.47557887491139206
0.4755607148862591
0.47554255760152675
0.4755244030565831
0.4755062512508162
0

0.46827086529904993
0.4682537921249524
0.4682367214527304
0.4682196532818444
0.46820258761175504
0.4681855244419236
0.4681684637718109
0.4681514056008781
0.4681343499285869
0.46811729675439867
0.46810024607777523
0.4680831978981783
0.46806615221507014
0.46804910902791286
0.4680320683361687
0.46801503013930046
0.46799799443677054
0.467980961228042
0.46796393051257773
0.467946902289841
0.46792987655929497
0.46791285332040317
0.4678958325726294
0.4678788143154373
0.4678617985482909
0.46784478527065443
0.46782777448199203
0.4678107661817681
0.4677937603694474
0.4677767570444947
0.4677597562063747
0.4677427578545527
0.46772576198849375
0.4677087686076634
0.4676917777115273
0.467674789299551
0.46765780337120033
0.4676408199259414
0.46762383896324056
0.4676068604825638
0.4675898844833779
0.4675729109651496
0.4675559399273455
0.4675389713694327
0.46752200529087845
0.4675050416911498
0.4674880805697146
0.46747112192604007
0.46745416575959403
0.4674372120698445
0.4674202608562597
0.4674033121183

0.4606569440472213
0.4606409695440659
0.46062499731022205
0.460609027345218
0.4605930596485829
0.4605770942198456
0.4605611310585349
0.46054517016418006
0.46052921153631027
0.4605132551744552
0.4604973010781443
0.46048134924690703
0.4604653996802734
0.4604494523777734
0.4604335073389371
0.4604175645632947
0.46040162405037655
0.460385685799713
0.46036974981083506
0.46035381608327325
0.46033788461655833
0.4603219554102216
0.4603060284637941
0.4602901037768072
0.46027418134879217
0.46025826117928076
0.46024234326780455
0.46022642761389554
0.4602105142170855
0.46019460307690674
0.46017869419289115
0.4601627875645716
0.46014688319148017
0.4601309810731497
0.46011508120911293
0.46009918359890273
0.46008328824205214
0.46006739513809447
0.46005150428656283
0.4600356156869909
0.46001972933891183
0.4600038452418598
0.45998796339536824
0.45997208379897137
0.4599562064522035
0.45994033135459844
0.4599244585056906
0.4599085879050149
0.45989271955210553
0.4598768534464974
0.4598609895877255
0.459845

0.4536008207525443
0.4535858341875904
0.4535708496902528
0.453555867260117
0.45354088689676814
0.4535259085997922
0.4535109323687744
0.45349595820330085
0.45348098610295706
0.4534660160673295
0.4534510480960039
0.4534360821885667
0.4534211183446041
0.45340615656370264
0.45339119684544893
0.4533762391894296
0.45336128359523137
0.4533463300624413
0.4533313785906463
0.45331642917943366
0.45330148182839036
0.45328653653710393
0.45327159330516187
0.4532566521321519
0.45324171301766153
0.4532267759612785
0.453211840962591
0.45319690802118684
0.4531819771366543
0.4531670483085816
0.4531521215365573
0.4531371968201697
0.45312227415900747
0.4531073535526595
0.45309243500071417
0.45307751850276096
0.45306260405838855
0.45304769166718634
0.4530327813287436
0.4530178730426497
0.4530029668084941
0.45298806262586644
0.45297316049435654
0.4529582604135543
0.4529433623830495
0.45292846640243234
0.45291357247129316
0.45289868058922195
0.4528837907558092
0.4528689029706458
0.45285401723332197
0.45283913

0.44698921517941365
0.4469751282626785
0.44696104323607727
0.4469469600992435
0.44693287885181043
0.44691879949341173
0.4469047220236811
0.4468906464422522
0.44687657274875897
0.44686250094283536
0.4468484310241153
0.44683436299223306
0.44682029684682284
0.446806232587519
0.44679217021395595
0.44677810972576837
0.44676405112259066
0.4467499944040576
0.44673593956980406
0.44672188661946494
0.44670783555267546
0.4466937863690705
0.4466797390682853
0.4466656936499551
0.44665165011371555
0.4466376084592019
0.44662356868605
0.4466095307938953
0.4465954947823738
0.44658146065112114
0.4465674283997735
0.446553398027967
0.44653936953533774
0.44652534292152196
0.44651131818615597
0.4464972953288765
0.44648327434931984
0.44646925524712266
0.446455238021922
0.4464412226733546
0.4464272092010572
0.446413197604667
0.44639918788382116
0.4463851800381569
0.4463711740673114
0.44635716997092234
0.4463431677486271
0.44632916740006334
0.4463151689248688
0.4463011723226813
0.4462871775931387
0.44627318473

0.44095520753187495
0.44094191992617726
0.4409286340579239
0.44091534992678777
0.44090206753244243
0.44088878687456134
0.44087550795281816
0.44086223076688613
0.4408489553164392
0.44083568160115094
0.4408224096206954
0.4408091393747462
0.4407958708629777
0.44078260408506376
0.4407693390406787
0.44075607572949665
0.440742814151192
0.4407295543054394
0.4407162961919129
0.4407030398102876
0.4406897851602378
0.4406765322414383
0.44066328105356406
0.44065003159629035
0.44063678386929167
0.4406235378722431
0.44061029360481996
0.4405970510666977
0.44058381025755156
0.4405705711770569
0.44055733382488926
0.4405440982007243
0.4405308643042374
0.44051763213510475
0.44050440169300187
0.4404911729776049
0.4404779459885898
0.4404647207256326
0.4404514971884094
0.44043827537659663
0.4404250552898706
0.44041183692790764
0.4403986202903844
0.44038540537697735
0.4403721921873633
0.4403589807212187
0.4403457709782208
0.44033256295804607
0.440319356660372
0.4403061520848753
0.44029294923123335
0.44027974

0.4348835650660095
0.4348710610278248
0.43485855858201083
0.43484605772827667
0.43483355846633276
0.43482106079588867
0.4348085647166549
0.4347960702283413
0.43478357733065826
0.4347710860233159
0.43475859630602465
0.4347461081784949
0.43473362164043733
0.4347211366915623
0.4347086533315805
0.4346961715602027
0.43468369137713964
0.43467121278210225
0.4346587357748014
0.4346462603549481
0.4346337865222533
0.43462131427642847
0.43460884361718455
0.4345963745442329
0.4345839070572848
0.43457144115605195
0.4345589768402455
0.4345465141095772
0.4345340529637587
0.4345215934025016
0.43450913542551794
0.4344966790325193
0.43448422422321786
0.43447177099732537
0.4344593193545541
0.4344468692946161
0.43443442081722355
0.4344219739220889
0.43440952860892423
0.4343970848774422
0.4343846427273552
0.43437220215837585
0.4343597631702168
0.4343473257625908
0.4343348899352103
0.4343224556877887
0.4343100230200385
0.4342975919316729
0.43428516242240484
0.43427273449194764
0.4342603081400143
0.434247883

In [21]:
print(w1,b1,w2,b2,w3,b3)

[[ 0.50961067 -0.00307415  0.19564319]
 [-0.12784775  0.46186633 -0.32694265]
 [-0.0177489   0.54906506 -0.50951467]
 [-0.07858022  0.09998425 -0.04878056]] [[-0.42583087]
 [ 0.32369097]
 [ 0.4666937 ]
 [ 0.100101  ]] [[0.44834559 0.37742121 0.43322411 0.51675263]
 [0.546318   0.33421917 0.40614772 0.84055598]
 [0.61333184 0.52472332 0.50152723 0.81839777]
 [0.68201156 0.16431894 0.64334387 0.8454928 ]
 [0.53002626 0.20279139 0.79613715 0.47891625]] [[0.57971771]
 [0.04939035]
 [0.32750931]
 [0.55829573]
 [0.38696641]] [[-0.87098087  0.645224    0.74456755  0.35075222  0.11150635]] [[-1.03762015]]


In [1]:
x_test=np.array([[1,0,1],[3,4,4]])
x_test.shape
predict(w1,w2,w3,b1,b2,b3,x_test)

NameError: name 'np' is not defined